### ISSUE TITLE
Could not find a declaration file for module 'react-native-diff-component'

### ISSUE THREAD

**Issue by nguyendinhduy13** [actuallydan/react-native-diff-component#3]

**Comment by actuallydan** [comment]
This wasn't written with typescript so it's not going to have any declaration files. I haven't used or updated this in.years. I would consider it unmaintained. Sorry for the inconvenience. There are however, react diff libraries you can easily modify to create your own react-native version (if a newer/better one doesn't exist), that's what I did here.
